<h1>Numpy</h1>

<h3>What is NumPy?</h3>
<p>NumPy is a Python library used for working with arrays.</p>
<p>NumPy is Faster than the lists</p>

In [196]:
import numpy as np


In [197]:
arr = np.array([1,2,3])

<h3>Dimensions in Arrays</h3>
<p>Arrays are a fundamental data structure in programming, and understanding their dimensions is crucial for efficient memory management and algorithm design. In this section, we will explore the concept of dimensions in arrays and how they impact the way we access and manipulate data.</p>

In [200]:
arr = np.array([1,2,3])
arr1 = np.array([[1,2,3],[4,5,6]])
arr2= np.array([[[1,2]],[[3,4]]])


In [204]:
print(arr.ndim)
print(arr1.ndim)

1
2


In [240]:
arr = np.array([1,2,3,4,5,6])
print(arr[-4:-1:2])

[3 5]


<h3>NumPy Array Indexing</h3>


In [248]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr1[0:,-2])

[2 5 8]


In [260]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
print(arr2[0])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


<h3>NumPy Array Slicing
</h3>

In [214]:
print(arr1[:])

[[1 2 3]
 [4 5 6]]


<h2>NumPy Data Types
</h2>


<h2>Data Types in NumPy</h2>

<p>NumPy has several extra data types and uses a single character to represent each type.</p>

<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Data Type</th>
<th>Character Representation</th>
<th>Description</th>
</tr>
<tr>
<td>Integer</td>
<td>i</td>
<td>Whole numbers, either positive, negative, or zero.</td>
</tr>
<tr>
<td>Boolean</td>
<td>b</td>
<td>True or False values.</td>
</tr>
<tr>
<td>Float</td>
<td>f</td>
<td>Decimal numbers.</td>
</tr>
<tr>
<td>Datetime</td>
<td>M</td>
<td>Specific dates and times.</td>
</tr>
<tr>
<td>String</td>
<td>S</td>
<td>Byte strings.</td>
</tr>
<tr>
<td>Unicode String</td>
<td>U</td>
<td>Unicode character strings.</td>
</tr>
</table>

<p>These data types enable efficient storage and manipulation of data in NumPy arrays.</p>

In [271]:
arr = np.array([True,False],dtype='i')
print(arr.dtype)
print(arr)

int32
[1 0]


<h3>NumPy Array Copy vs View
</h3>
<p>The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.</p>

In [280]:
arr = np.array([1,2,3,4,5])
arr1 = arr.view()
arr1[0] = 5
print(arr)

[5 2 3 4 5]


<h2>NumPy Array Shape
</h2>

In [283]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


<h3>NumPy Array Reshaping</h3>

In [291]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr.reshape(4,2,2))


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


<h3>NumPy Joining Array</h3>

In [296]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [303]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[14,15,16]])
arr = np.concatenate((arr1,arr2),axis = )
print(arr)

AxisError: axis 2 is out of bounds for array of dimension 2

<h3>NumPy Splitting Array</h3>

In [309]:
arr = np.array([1,2,3])
new = np.array_split(arr,4)

print(new)

[array([1]), array([2]), array([3]), array([], dtype=int32)]


In [313]:
arr1 = np.array([[1,2,3],[4,5,6]])
new = np.array_split(arr1,2)
print(new)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


<h3>NumPy Sorting Arrays
</h3>

In [320]:
arr = np.array([1,5,3,5,6,7])
print(np.mean(arr))

4.5


Here is the content in correct HTML format:



<h1>NumPy Cheat Sheet</h1>

<h2>NumPy Basics</h2>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Operator</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>np.array([1,2,3])</code></td>
    <td>1D array</td>
  </tr>
  <tr>
    <td><code>np.array([(1,2,3),(4,5,6)])</code></td>
    <td>2D array</td>
  </tr>
  <tr>
    <td><code>np.arange(start,stop,step)</code></td>
    <td>Range array</td>
  </tr>
</table>

<h2>Placeholders</h2>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Operator</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>np.linspace(0,2,9)</code></td>
    <td>Add evenly spaced values between interval to array of length</td>
  </tr>
  <tr>
    <td><code>np.zeros((1,2))</code></td>
    <td>Create an array filled with zeros</td>
  </tr>
  <tr>
    <td><code>np.ones((1,2))</code></td>
    <td>Create an array filled with ones</td>
  </tr>
  <tr>
    <td><code>np.random.random((5,5))</code></td>
    <td>Create a random array</td>
  </tr>
  <tr>
    <td><code>np.empty((2,2))</code></td>
    <td>Create an empty array</td>
  </tr>
</table>

<h2>Array</h2>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Operator</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>array.shape</code></td>
    <td>Dimensions (Rows, Columns)</td>
  </tr>
  <tr>
    <td><code>len(array)</code></td>
    <td>Length of array</td>
  </tr>
  <tr>
    <td><code>array.ndim</code></td>
    <td>Number of array dimensions</td>
  </tr>
  <tr>
    <td><code>array.dtype</code></td>
    <td>Data type</td>
  </tr>
  <tr>
    <td><code>array.astype(type)</code></td>
    <td>Convert to data type</td>
  </tr>
  <tr>
    <td><code>type(array)</code></td>
    <td>Type of array</td>
  </tr>
</table>

<h2>Copying/Sorting</h2>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Operator</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>np.copy(array)</code></td>
    <td>Create copy of array</td>
  </tr>
  <tr>
    <td><code>other = array.copy()</code></td>
    <td>Create deep copy of array</td>
  </tr>
  <tr>
    <td><code>array.sort()</code></td>
    <td>Sort array</td>
  </tr>
  <tr>
    <td><code>array.sort(axis=0)</code></td>
    <td>Sort axis of array</td>
  </tr>
</table>

<h1>Array Manipulation</h1>

<h2>Adding or Removing Elements</h2>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Operator</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>np.append(a,b)</code></td>
    <td>Append items to array</td>
  </tr>
  <tr>
    <td><code>np.insert(array, 1, 2, axis)</code></td>
    <td>Insert items into array at axis 0 or 1</td>
  </tr>
  <tr>
    <td><code>np.resize((2,4))</code></td>
    <td>Resize array to shape (2,4)</td>
  </tr>


Here is the rest of the content in correct HTML format:


<h2>Combining Arrays</h2>
<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
<tr>
<td><code>np.concatenate((a,b),axis=0)</code></td>
<td>Split an array into multiple sub-arrays</td>
</tr>
<tr>
<td><code>np.vstack((a,b))</code></td>
<td>Split an array into sub-arrays of (nearly) identical size</td>
</tr>
<tr>
<td><code>np.hstack((a,b))</code></td>
<td>Split the array horizontally at 3rd index</td>
</tr>
</table>


<h2>More</h2>
<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
<tr>
<td><code>other = ndarray.flatten()</code></td>
<td>Flattens a 2D array to 1D</td>
</tr>
<tr>
<td><code>array = np.transpose(other)</code></td>
<td>Transpose array</td>
</tr>
<tr>
<td><code>array.T</code></td>
<td>Transpose array</td>
</tr>
<tr>
<td><code>inverse = np.linalg.inv(matrix)</code></td>
<td>Inverse of a given matrix</td>
</tr>
</table>


<h1>Slicing and Subsetting</h1>
<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
<tr>
<td><code>array[i]</code></td>
<td>1D array at index i</td>
</tr>
<tr>
<td><code>array[i,j]</code></td>
<td>2D array at index [i][j]</td>
</tr>
<tr>
<td><code>array[i<4]</code></td>
<td>Boolean Indexing</td>
</tr>
<tr>
<td><code>array[0:3]</code></td>
<td>Select items of index 0, 1, and 2</td>
</tr>
<tr>
<td><code>array[0:2,1]</code></td>
<td>Select items of rows 0 and 1 at column 1</td>
</tr>
<tr>
<td><code>array[:1]</code></td>
<td>Select items of row 0 (equals array[0:1, :])</td>
</tr>
<tr>
<td><code>array[1:2, :]</code></td>
<td>Select items of row 1</td>
</tr>
<tr>
<td><code>array[1,...]</code></td>
<td>Select items of row 1</td>
</tr>
<tr>
<td><code>array[ : :-1]</code></td>
<td>Reverses array</td>
</tr>
</table>


<h1>Mathematics</h1>


<h2>Operations</h2>
<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
<tr>
<td><code>np.add(x,y)</code></td>
<td>Addition</td>
</tr>
<tr>
<td><code>np.subtract(x,y)</code></td>
<td>Subtraction</td>
</tr>
<tr>
<td><code>np.divide(x,y)</code></td>
<td>Division</td>
</tr>
<tr>
<td><code>np.multiply(x,y)</code></td>
<td>Multiplication</td>
</tr>
<tr>
<td><code>np.sqrt(x)</code></td>
<td>Square Root</td>
</tr>
<tr>
<td><code>np.sin(x)</code></td>
<td>Element-wise sine</td>
</tr>
<tr>

<tr>
<td><code>np.cos(x)</code></td>
<td>Element-wise cosine</td>
</tr>
<tr>
<td><code>np.log(x)</code></td>
<td>Element-wise natural log</td>
</tr>
<tr>
<td><code>np.dot(x,y)</code></td>
<td>Dot product</td>
</tr>
<tr>
<td><code>np.roots([1,0,-4])</code></td>
<td>Roots of a given polynomial coefficients</td>
</tr>





<h2>Comparison</h2>
<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
<tr>
<td><code>==</code></td>
<td>Equal</td>
</tr>
<tr>
<td><code>!=</code></td>
<td>Not equal</td>
</tr>
<tr>
<td><code>&lt;</code></td>
<td>Smaller than</td>
</tr>
<tr>
<td><code>&gt;</code></td>
<td>Greater than</td>
</tr>
<tr>
<td><code>&lt;=</code></td>
<td>Smaller than or equal</td>
</tr>
<tr>
<td><code>&gt;=</code></td>
<td>Greater than or equal</td>
</tr>
<tr>
<td><code>np.array_equal(x,y)</code></td>
<td>Array-wise comparison</td>
</tr>
</table>


<h1>Basic Statistics</h1>
<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
<tr>
<td><code>np.mean(array)</code></td>
<td>Mean</td>
</tr>
<tr>
<td><code>np.median(array)</code></td>
<td>Median</td>
</tr>
<tr>
<td><code>array.corrcoef()</code></td>
<td>Correlation Coefficient</td>
</tr>
<tr>
<td><code>np.std(array)</code></td>
<td>Standard Deviation</td>
</tr>
</table>


<h2>More</h2>
<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
<tr>
<td><code>array.sum()</code></td>
<td>Array-wise sum</td>
</tr>
<tr>
<td><code>array.min()</code></td>
<td>Array-wise minimum value</td>
</tr>
<tr>
<td><code>array.max(axis=0)</code></td>
<td>Maximum value of specified axis</td>
</tr>
<tr>
<td><code>array.cumsum(axis=0)</code></td>
<td>Cumulative sum of specified axis</td>
</tr>
</table>


